- name: Démarrer Minikube
  command: minikube start
  become: false

- name: Déployer le backend
  command: kubectl apply -f backend-deployment.yaml
  args:
    chdir: /home/dieye-stech/Projet-Systeme-Repartie/projet_SystemeRepartie

- name: Déployer le frontend
  command: kubectl apply -f frontend-deployment.yaml
  args:
    chdir: /home/dieye-stech/Projet-Systeme-Repartie/projet_SystemeRepartie

- name: Déployer PostgreSQL
  command: kubectl apply -f postgres-deployment.yaml
  args:
    chdir: /home/dieye-stech/Projet-Systeme-Repartie/projet_SystemeRepartie